name: Deploy Firestore Rules

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy-rules:
    name: Deploy Firestore rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Firestore rules
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only firestore:rules --project twilight-engineering
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
